**SVD** **Decomposition**

In [86]:
import numpy as np
import sympy as sp
np.random.seed(14)
A = np.random.randint(0,10,(5,5))
print(A)

[[8 6 7 9 6]
 [0 8 9 7 6]
 [0 7 4 0 6]
 [4 5 5 8 5]
 [9 8 7 3 4]]


In [87]:
U,S,Vt=np.linalg.svd(A)
sp.Matrix(np.round(U))

Matrix([
[-1.0,    0,    0,    0, -1.0],
[   0, -1.0,    0,  1.0,    0],
[   0, -1.0,    0, -1.0,    0],
[   0,    0,    0,    0,  1.0],
[   0,    0, -1.0,    0,    0]])

In [88]:
A=sp.Matrix(A)
A

Matrix([
[8, 6, 7, 9, 6],
[0, 8, 9, 7, 6],
[0, 7, 4, 0, 6],
[4, 5, 5, 8, 5],
[9, 8, 7, 3, 4]])

In [89]:
sp.Matrix(U)
U

array([[-0.54336961,  0.41653236,  0.23614937, -0.27190268, -0.63368184],
       [-0.48586941, -0.5754709 ,  0.30831618,  0.57365169, -0.09289258],
       [-0.27492881, -0.59173735, -0.47722204, -0.58307844, -0.08086848],
       [-0.41396641,  0.10507829,  0.41057165, -0.34823697,  0.72646562],
       [-0.47087827,  0.36625059, -0.6729522 ,  0.36843346,  0.23564015]])

In [90]:
Vt=sp.Matrix(Vt)
Vt

Matrix([
[ -0.351322612205806, -0.511458289524165, -0.502318179511639,  -0.446524674209967, -0.404073015782668],
[   0.84902918068075, -0.336215882953428, -0.185650988583993,   0.199931217563942, -0.302769795527239],
[ -0.376344527469379, -0.415512762827381, -0.020687663404851,   0.827075632176499, -0.035097860534476],
[-0.0951972766612657, 0.0311444494184333,   0.66608097853071, -0.0423244091000082, -0.737910750850405],
[-0.0708812222354457,  0.672122358893707, -0.518766139596947,   0.273491803568702, -0.446442955816292]])

In [91]:
Sigma=np.zeros((A.shape[0],A.shape[1]))

In [92]:
Sigma[:A.shape[1],:A.shape[0]]=np.diag(S)
Sigma=sp.Matrix(Sigma)
Sigma

Matrix([
[29.1490687169048,                0,                0,                0,                 0],
[               0, 8.30222035212742,                0,                0,                 0],
[               0,                0, 6.70951230663089,                0,                 0],
[               0,                0,                0, 2.64995126917397,                 0],
[               0,                0,                0,                0, 0.604262393383368]])

In [93]:
B=U@Sigma@Vt
B

Matrix([
[                 8.0,              6.0,              7.0,      9.00000000000001, 6.0],
[7.99707522425308e-15, 8.00000000000001, 9.00000000000001,      6.99999999999999, 6.0],
[5.81219100626029e-15, 7.00000000000001,              4.0, -7.54431239702313e-15, 6.0],
[                 4.0,              5.0,              5.0,                   8.0, 5.0],
[                 9.0,              8.0,              7.0,      3.00000000000001, 4.0]])

In [94]:
A

Matrix([
[8, 6, 7, 9, 6],
[0, 8, 9, 7, 6],
[0, 7, 4, 0, 6],
[4, 5, 5, 8, 5],
[9, 8, 7, 3, 4]])

In [95]:
U1=U[:,:2]
U1=sp.Matrix(U1)
U1

Matrix([
[-0.543369608401009,  0.416532357113768],
[-0.485869407476142, -0.575470899164334],
[-0.274928812211558, -0.591737354563774],
[-0.413966407770596,  0.105078291217324],
[-0.470878274077674,  0.366250591290929]])

In [96]:

Vt1=Vt[:2,:]
Vt1=sp.Matrix(Vt1)
Vt1

Matrix([
[-0.351322612205806, -0.511458289524165, -0.502318179511639, -0.446524674209967, -0.404073015782668],
[  0.84902918068075, -0.336215882953428, -0.185650988583993,  0.199931217563942, -0.302769795527239]])

In [97]:

Sig1=Sigma[:2,:2]
Sig1=sp.Matrix(Sig1)
Sig1

Matrix([
[29.1490687169048,                0],
[               0, 8.30222035212742]])

In [98]:
A2=U1@Sig1@Vt1
print('Rank 2 Aproximation of A')
A2

Rank 2 Aproximation of A


Matrix([
[ 8.50056446894146, 6.93816090330327, 7.31406827545758, 7.76376924192916, 5.35297719627296],
[ 0.91926093324513, 8.84993399901505,  8.0011340848246,  5.3687599237208, 7.16928003489592],
[-1.35558354429156, 5.75052439064276, 4.93759102886981, 2.59620362708467, 4.72563579453602],
[ 4.97999568698638, 5.87832271596941, 5.89938170164433, 5.56251165463994, 4.61171084856514],
[ 7.40377302100206,  5.9977748869126,  6.3301424529265, 6.73677675089927, 4.62554007798512]])

In [99]:
U2=U[:,:3]
U2=sp.Matrix(U1)
U2

Matrix([
[-0.543369608401009,  0.416532357113768],
[-0.485869407476142, -0.575470899164334],
[-0.274928812211558, -0.591737354563774],
[-0.413966407770596,  0.105078291217324],
[-0.470878274077674,  0.366250591290929]])

In [100]:
Vt2=Vt[:3,:]
Vt2=sp.Matrix(Vt2)
Vt2

Matrix([
[-0.351322612205806, -0.511458289524165, -0.502318179511639, -0.446524674209967, -0.404073015782668],
[  0.84902918068075, -0.336215882953428, -0.185650988583993,  0.199931217563942, -0.302769795527239],
[-0.376344527469379, -0.415512762827381, -0.020687663404851,  0.827075632176499, -0.035097860534476]])

In [101]:
Sig2=Sigma[:3,:3]
Sig2=sp.Matrix(Sig2)
Sig2

Matrix([
[29.1490687169048,                0,                0],
[               0, 8.30222035212742,                0],
[               0,                0, 6.70951230663089]])

In [102]:
A3=U1@Sig1@Vt1
print('Rank 3 Aproximation of A')
A3

Rank 3 Aproximation of A


Matrix([
[ 8.50056446894146, 6.93816090330327, 7.31406827545758, 7.76376924192916, 5.35297719627296],
[ 0.91926093324513, 8.84993399901505,  8.0011340848246,  5.3687599237208, 7.16928003489592],
[-1.35558354429156, 5.75052439064276, 4.93759102886981, 2.59620362708467, 4.72563579453602],
[ 4.97999568698638, 5.87832271596941, 5.89938170164433, 5.56251165463994, 4.61171084856514],
[ 7.40377302100206,  5.9977748869126,  6.3301424529265, 6.73677675089927, 4.62554007798512]])