 **Q.2**

*Row Echelon Form*

In [52]:

import numpy as np
import sympy as sp
np.random.seed(14)
A = np.random.randint(0,10,(5,5))
print(A)

[[8 6 7 9 6]
 [0 8 9 7 6]
 [0 7 4 0 6]
 [4 5 5 8 5]
 [9 8 7 3 4]]


In [53]:
A=sp.Matrix(A)
A

Matrix([
[8, 6, 7, 9, 6],
[0, 8, 9, 7, 6],
[0, 7, 4, 0, 6],
[4, 5, 5, 8, 5],
[9, 8, 7, 3, 4]])

In [54]:
A[3:4,0:5]=8*A[3:4,0:5]-4*A[0:1,0:5]
A

Matrix([
[8,  6,  7,  9,  6],
[0,  8,  9,  7,  6],
[0,  7,  4,  0,  6],
[0, 16, 12, 28, 16],
[9,  8,  7,  3,  4]])

In [55]:
A[4:5,0:5]=8*A[4:5,0:5]-9*A[0:1,0:5]
A

Matrix([
[8,  6,  7,   9,   6],
[0,  8,  9,   7,   6],
[0,  7,  4,   0,   6],
[0, 16, 12,  28,  16],
[0, 10, -7, -57, -22]])

In [56]:
A[2:3,0:5]=8*A[2:3,0:5]-7*A[1:2,0:5]
A

Matrix([
[8,  6,   7,   9,   6],
[0,  8,   9,   7,   6],
[0,  0, -31, -49,   6],
[0, 16,  12,  28,  16],
[0, 10,  -7, -57, -22]])

In [57]:
A[3:4,0:5]=8*A[3:4,0:5]-16*A[1:2,0:5]
A

Matrix([
[8,  6,   7,   9,   6],
[0,  8,   9,   7,   6],
[0,  0, -31, -49,   6],
[0,  0, -48, 112,  32],
[0, 10,  -7, -57, -22]])

In [58]:
A[4:5,0:5]=8*A[4:5,0:5]-10*A[1:2,0:5]
A

Matrix([
[8, 6,    7,    9,    6],
[0, 8,    9,    7,    6],
[0, 0,  -31,  -49,    6],
[0, 0,  -48,  112,   32],
[0, 0, -146, -526, -236]])

In [59]:
A[3:4,0:5]=31*A[3:4,0:5]-48*A[2:3,0:5]
A

Matrix([
[8, 6,    7,    9,    6],
[0, 8,    9,    7,    6],
[0, 0,  -31,  -49,    6],
[0, 0,    0, 5824,  704],
[0, 0, -146, -526, -236]])

In [60]:
A[4:5,0:5]=31*A[4:5,0:5]-146*A[2:3,0:5]
A

Matrix([
[8, 6,   7,     9,     6],
[0, 8,   9,     7,     6],
[0, 0, -31,   -49,     6],
[0, 0,   0,  5824,   704],
[0, 0,   0, -9152, -8192]])

In [61]:
A[4:5,0:5]=5824*A[4:5,0:5]+9152*A[3:4,0:5]
A

Matrix([
[8, 6,   7,    9,         6],
[0, 8,   9,    7,         6],
[0, 0, -31,  -49,         6],
[0, 0,   0, 5824,       704],
[0, 0,   0,    0, -41267200]])